version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile.pub
    image: backend
    restart: always
    env_file: .env
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile.pub
    image: frontend
    env_file: .env
    restart: always
    ports:
      - '8080:80'
    networks:
      - frontend
      
  postgres:
    container_name: db
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/data/postgres
    restart: always
    networks:
      - backend

  adminer: 
    image: adminer
    restart: always
    ports: 
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend: